config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  
  resources :users
  
  resources :posts
  
  get 'homes/about' =>'homes#about',as:'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
      image
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
   has_many :posts, dependent: :destroy
   
   has_one_attached :profile_image

  validates :name, uniqueness: true, length: {in: 2..20}
  validates :introduction, length: {maximum: 100}

  def get_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
      profile_image
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?
   
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    about_path
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "投稿しました"
      redirect_to posts_path
    else
      @posts = Post.all
      @user = current_user
      render :index
    end
  end

  def index
    @posts = Post.all
    @user = current_user
  end

  def show
    @post = Post.find(params[:id])
    @posts = Post.all
    @user = @post.user

  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "更新しました"
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "削除しました"
    @posts = Post.all
    @user = current_user
    render :index

  end

  private

  def post_params
    params.require(:post).permit(:title, :image, :body)
  end
  
  def correct_user
    @post = Post.find(params[:id])
    @user = @post.user
    redirect_to posts_path unless @user == current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @user = current_user
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = current_user
    user_id = params[:id].to_i
    login_user_id = current_user.id
    if(user_id != login_user_id)
    redirect_to post_images_path
    end
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "更新しました"
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def correct_user
    @user = User.find(params[:id])
    @users = @user
    redirect_to user_path(current_user.id) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-10">
        <h2>
          <strong>Fantasy</strong>は幻想的な[イラスト・写真]専用の投稿サイトです！
        </h2>
        <div class="col-6 mx-auto">
          <div class="row">
            <p>この度はFantasyをご利用いただき誠にありがとうございます。
               管理人の〇〇と申します。
               幻想的な写真やイラストが好きでそれを共有したくこのサイトを作成いたしました。
               みなさんがみて感じたことを自由に投稿していただければと思います。
               これから末永くよろしくお願いいたします。
            </p> 
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-10">
        <h2>
          <strong>Fantasy</strong>は幻想的な[イラスト・写真]専用の投稿サイトです！
        </h2>
        <div class="btn-wrapper col-4 mx-auto">
          <div class="row">
            <%= link_to "ログインする", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign-in text-white" %>
          </div>
          <div class="row">
              <%= link_to "ユーザー登録する（無料）", new_user_registration_path, class: "btn btn-success btn-sm btn-block mb-3 sign-in text-white" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fantasy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#1a1a1a;">
        <div class="container">
          <a class="navbar-brand" href="/" >
            <span>Fantasy</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user.id), class: 'nav-link text-light ' do %>
               <i class="fas fa-home"></i>
               マイページ
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  users_path, class: 'nav-link text-light ' do %>
                <i class="fas fa-users"></i>
                ユーザー
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to posts_path, class: 'nav-link text-light ' do %>
                <i class="fas fa-post-open"></i>
                投稿一覧
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light ' do %>
                <i class="fas fa-sign-out-alt"></i>
                ログアウト
              <% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: "nav-link text-light " do %>
                <i class="fas fa-home"></i>
                ホーム
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-light text-white' do %>
                <i class="fas fa-link"></i>
                お知らせ
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light ' do %>
                <i class="fas fa-user-plus"></i>
                新規登録
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-light ' do %>
                <i class="fas fa-sign-in-alt"></i>
                ログイン
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= flash[:notice] %>
    <main class="mb-auto">
    <%= yield %>

  </body>
</html>

app/views/posts/edit.html.erb
<% if @post.errors.any? %>
  <%= @post.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>投稿編集</h1>
        <%= form_with model: @post, url: post_path(@post.id), method: :patch do |f| %>
          <div class="form-group">
            <label for="post_title">画像</label><br>
              <%= image_tag @post.get_image %>
          </div>    
          <div class="form-group">
            <label for="post_title">場所</label><br>
              <%= f.text_field :title %>
          </div>
          <div class="form-group">
            <label for="post_opinion">説明</label><br>
              <%= f.text_area :body %>
          </div>
          <div class="form-group">
            <%= f.submit '更新する', class: 'btn btn-success' %>
          </div>
        <% end %>
          <%= link_to "戻る", post_path(@post.id) %>
    </div>
  </div>
</div>
     

app/views/posts/index.html.erb
<%= render 'users/sidebox', post: @post, user: @user %>

<div class="col-md-8 offset-md-1">
  <h2>投稿一覧</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>投稿ユーザー</th>
          <th>場所</th>
          <th>説明</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      
      <tbody>
        <% @posts.each do |post| %>
        <tr>
          <td><%= link_to post_path(post.id) do %>
                <%= image_tag post.get_image, size: "150x150" %>
              <% end %>
          </td>
          <td>
           <%= image_tag post.user.get_image, size: "50x50" %> <%= post.user.name %>
          </td>
          <td>
            <%= post.title %>
          </td>
          <td>
            <%= post.body %>
          </td>
        <% end %>
      </tbody>
    </table>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-10 px-sm-0 mx-auto">
      <h1>投稿フォーム</h1>
        <%= form_with model: @post do |f| %>
      <h4>画像</h4>
        <%= f.file_field :image, accept: "image/*" %>
      <h4>場所</h4>
        <%= f.text_field :title %>
      <h4>説明</h4>
        <%= f.text_area :body %>
      <%= f.submit '投稿' %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<%= render 'users/sidebox', post: @post, user: @user %>

<div class="col-md-8 offset-md-1">
 <h2><%= @user.name %> の投稿</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>投稿者</th>
          <th>場所</th>
          <th>説明</th>
          <th colspan="3"></th>
        </tr>
      </thead>
        
        <tbody>
          <tr>
            <td>
              <%= image_tag @post.get_image, size: "300x300" %>
            </td>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= image_tag @user.get_image, size: "150x150" %><br>
                <%= @user.name %>
              <% end %>
            </td>
            <td><%= @post.title %></td>
            <td><%= @post.body %></td>
            <% if @post.user == current_user %>
              <td><%= link_to "Edit", edit_post_path(@post.id), class: "btn btn-success btn-sm text-white" %></td>
              <td>
                <%= link_to "Destroy", post_path(@post.id), method: "delete", "data-confirm" => "本当に削除しますか？", class: "btn btn-danger btn-sm text-white" %>
            <% end %>  
            </td>
          </tr>
        </tbody>

app/views/users/_sidebox.html.erb
<body>
  <main>
    <div class="container px-5 px-sm-0">
      <div class="row">     
        <div class="col-md-3">
          <h1>ユーザー</h1>
            <% if current_user.profile_image.attached? %>
              <%= image_tag current_user.profile_image, size: "150x150" %>
            <% else %>
              <%= image_tag 'no_image.jpg', size: "150x150" %>
            <% end %>
              <table class="table">
                <tbody>
                  <tr>
                    <th>
                      【名前】<br>
                      <%= user.name %>
                    </th>
                  </tr>
                  <tr>
                    <th>
                      【自己紹介】<br>
                      <%= user.introduction %>
                    </th>
                  </tr>
                  
                  </tbody>
              </table>
                <div class="row">
                  <%= link_to edit_user_path(user.id),class: "btn btn-outline-secondary btn-block" do %>
                    プロフィール編集
                  <% end %>
                </div>
                <div class="row">
                  <%= link_to new_post_path(user.id),class: "btn btn-outline-secondary btn-block" do %>
                    新規投稿
                  <% end %>
                </div>
        </div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <body>
      <main>
        <div class="container">
          <div class="row">
            <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
              <h2>プロフィール編集</h2>
                <%= form_with model: @user do |f| %>
                <div class="form-group">
                      <label for="user_image">Image</label><br>
                        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>  
                  </div>
                  <div class="form-group">
                      <label for="user_name">名前</label><br>
                        <%= f.text_field :name, class: "form-controll name"%>
                  </div>
                  <div class="form-group">
                      <label for="user_introduction">自己紹介</label><br>
                        <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction" %>
                  </div>
                  <div class="form-group">
                    <%= f.submit "保存", class: "btn btn-secondary"%>
                  </div>
                <% end %>
            </div>
          </div>
        </div>
      </main>
  </body>

app/views/users/index.html.erb
<%= render 'users/sidebox', post: @post, user: @user %>
<div class="col-md-8 offset-md-1">
  <h2>アカウント一覧</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>名前</th>
          <th>自己紹介</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_image, size: "60x60" %></td>
            <td><%= user.name %></td>
            <td><%= user.introduction %></td>
          </tr>
        <% end %>
      </tbody>

app/views/users/show.html.erb
<%= render 'users/sidebox', post: @post, user: @user %>

<div class="col-md-8 offset-md-1">
          <h2><%= @user.name %> の投稿</h2>
            <table class="table table-hover table-inverse">
              <thead>
                <tr>
                  <th></th>
                  <th>場所</th>
                  <th>説明</th>
                  <th colspan="3"></th>
                </tr>
              <tbody>
                <% @posts.each do |post| %>
                  <tr>
                    <td>
                      <%= link_to post_path(post.id) do %>
                          <%= image_tag post.get_image, size: "150x150" %>
                      <% end %>
                    </td>
                    <td>
                      <%=  post.title %>
                    </td>
                    <td><%= post.body %></td>
                  </tr>
                <% end %>
              </tbody>